Merging install.sh and init.sh
grapheo12/iqps pull request #40
Opened 2020-12-17 10:44 UTC by pasthorizon

Merged **install.sh** and **init.sh** to eliminate the need to run two different scripts. The need for manually stopping the `docker-compose up` is eliminated by redirecting the logs to text file and periodically running a pattern match for "_mysqld: ready for connections_".
The command `docker-compose up` is given from a different terminal. When the pattern matches, we stop the process and the newly created terminal is closed. We have appended the **init.sh** script to **install.sh** , which ensures its running as soon as the process is killed.

2020-12-19 13:41 UTC, grapheo12 requested changes
Good work! But there are some necessary changes. Please look into them tonight. I'll merge tomorrow.

2020-12-19 13:41 UTC, grapheo12 commented on install.sh
> +gnome-terminal -- docker-compose up
Do not expect that people will be using gnome-terminal. I use Konsole myself.

2020-12-19 13:41 UTC, grapheo12 commented on install.sh
> +gnome-terminal -- docker-compose up
Can you try with `docker-compose up -d`? Then I guess you'll not have to rely on a separate window in the terminal.

2020-12-19 14:09 UTC, grapheo12 commented
Is `init.sh` unnecessary now? Please delete it if that is the case.

2020-12-20 03:20 UTC, pasthorizon commented
@grapheo12 Changes made:)

2020-12-20 10:16 UTC, grapheo12 commented
@pasthorizon There is a merge conflict due to #39. Please resolve it. Looks good to me otherwise.
After removing conflict, please check if:
1. Pause resume functionality works as expected.
2. Your feature also works as expected.
Then commit. I'll merge.

2020-12-20 16:30 UTC, pasthorizon commented
Hey @grapheo12 I have made the changes. Kindly look into it

2020-12-20 17:13 UTC, grapheo12 commented
Hey! There are still merge conflicts remaining. There is a whole chunk of commented out code. Please see.
Don't worry about midevals. I'll handle them.

2020-12-20 19:01 UTC, merged